//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int ID_Cancellation { get; set; }
        public int ID_Ticket { get; set; }
        public int ID_Passenger { get; set; }
        public System.DateTime Cancellation_Date { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Refund { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Det_Ticket Det_Ticket { get; set; }
    }
}
