//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Luggage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight_Luggage()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID_Luggage { get; set; }
        public int ID_Passenger { get; set; }
        public string Luggage_Type { get; set; }
        public decimal Luggage_Weight { get; set; }
        public decimal Extra_Luggage { get; set; }
        public Nullable<decimal> Total_Extra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
