//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Stops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight_Stops()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID_FlightStops { get; set; }
        public int ID_Passenger { get; set; }
        public bool Transhipment { get; set; }
        public bool Partner_Airline { get; set; }
        public string Airport { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public Nullable<decimal> Transhipment_Price { get; set; }
        public Nullable<decimal> PA_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
