//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        public int ID_Itinerary { get; set; }
        public int ID_Flight { get; set; }
        public int ID_Ticket { get; set; }
        public string Airline { get; set; }
        public string Country_Origin { get; set; }
        public Nullable<System.DateTime> Departure_DateTime { get; set; }
        public string Country_Destination { get; set; }
        public Nullable<System.DateTime> Arrival_DateTime { get; set; }
        public int ID_Flight_Class { get; set; }
        public Nullable<int> ID_Passenger { get; set; }
    
        public virtual Det_Ticket Det_Ticket { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Flight_Class Flight_Class { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
