//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visa
    {
        public int ID_Visa { get; set; }
        public int ID_Passport { get; set; }
        public int ID_Passenger { get; set; }
        public string Issuing_Postname { get; set; }
        public string Control_Number { get; set; }
        public string Visa_Num { get; set; }
        public string Visa_Type { get; set; }
        public string Visa_Class { get; set; }
        public string Entries { get; set; }
        public string Annotation { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Passport Passport { get; set; }
    }
}
